<div class="container mt-4">
    <form method="POST" action="<?= SITE_URL; ?>/auth/saveRegisterData">
        <div class="row">
            <!-- <div class="col">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input id="name" name="name" type="text" class="form-control" placeholder="" aria-describedby="helpId">
                    <small id="helpId" class="text-muted">Help text</small>
                </div>
            </div> -->
            <div class="col">
                <div class="form-group">
                    <label for="login">E-mail</label>
                    <input id="login" name="login" type="email" class="form-control" placeholder="" aria-describedby="helpId">
                    <small id="helpId" class="text-muted">Help text</small>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="password">Senha</label>
                    <input id="password" name="password" type="password" class="form-control" placeholder="" aria-describedby="helpId">
                    <small id="helpId" class="text-muted">Help text</small>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="confirmPassword">Confirmar Senha</label>
                    <input id="confirmPassword" name="confirmPassword" type="password" class="form-control" placeholder="" aria-describedby="helpId">
                    <small id="helpId" class="text-muted">Help text</small>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group row">
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="acceptTerm">
                            <label class="form-check-label" for="acceptTerm">
                                Aceito Termos
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-success">Registrar</button>
            </div>
        </div>
    </form>
</div>
