<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="<?= IMG_PATH;?>favicon/favicon.ico" rel="icon" type="image/x-icon">
        <link rel="stylesheet" href="<?= CSS_PATH;?>/bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="<?= CSS_PATH;?>/bootstrap/bootstrap.min.css.map">

        <title>Financial - Management</title>
    </head>
    <body>
        <div class="container">