<?php

define('PATH_URL', __DIR__);
define('SITE_URL', '');

define('ASSETS_PATH', DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR);

define('VIEWS_PATH', PATH_URL . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR);
define('INCLUDE_PATH', VIEWS_PATH . 'includes' . DIRECTORY_SEPARATOR);

define('CSS_PATH', ASSETS_PATH . 'css' . DIRECTORY_SEPARATOR);
define('JS_PATH', ASSETS_PATH .  'js' . DIRECTORY_SEPARATOR);
define('IMG_PATH', ASSETS_PATH . 'img' . DIRECTORY_SEPARATOR);
define('FONTS_PATH', ASSETS_PATH . 'fonts' . DIRECTORY_SEPARATOR);
define('VENDOR_PATH', ASSETS_PATH . 'vendor' . DIRECTORY_SEPARATOR);
