<div class="row align-items-center">
    <div class="col text-center">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-3">Página Não Encontrada</p>
        <p class="text-gray-500 mb-1">Parece que há uma falha na matrix...</p>
        <a href="/" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span class="text">Voltar para a <strong><span class="text-info">HOME</span></strong></span>
        </a>
    </div>
</div>