<div class="col">
    <h1>Teste</h1>
</div>
<div class="row">
    <?php if (count($this->categorias) > 0) : ?>
        <?php foreach ($this->categorias as $categoria) : ?>
            <div class="col">
                <h1>Categoria: <?= $categoria['name']; ?></h1>
                <h4>Descrição: <?= $categoria['description']; ?></h4>
                <small>Criado em: <?= $categoria['created_at']; ?></small>
            </div>
        <?php endforeach; ?>
    <?php else : ?>
        <div class="col">
            <h1>Nenhum registro encontrado!</h1>
        </div>
    <?php endif; ?>
</div>
